### ISSUE TITLE
Update README usage example

### ISSUE THREAD

**Issue by driesmarzougui** [rubensworks/GraphQL-LD.js#12]
The usage example ['with a client-side query engine'](https://github.com/rubensworks/graphql-ld.js#with-a-client-side-query-engine) gives errors.

Fix: 

```js
const comunicaConfig = {
  sources: [
    { type: "sparql", value: "http://dbpedia.org/sparql" },
    { type: "file", value: "https://ruben.verborgh.org/profile/" },
    { type: "hypermedia", value: "https://fragments.linkedsoftwaredependencies.org/npm" },
  ],
};
```

Should be

```js
const comunicaConfig = {
  sources: [
    "http://dbpedia.org/sparql" ,
    "https://ruben.verborgh.org/profile/",
    "https://fragments.linkedsoftwaredependencies.org/npm",
  ],
};
```

(Linked to [issue](https://github.com/comunica/comunica/issues/490))

**Comment by rubensworks** [comment]
Thanks for reporting!

Note to self: things should be backwards-compatible, but it looks like things are going wrong after all. In any case, it's good to update the README.

**Comment by rubensworks** [comment]
Done in b60c7584569f18d4df2e954eb868143b697fa6ba
