### ISSUE TITLE
Block for you

### ISSUE THREAD

**Issue by shaqura** [rubensworks/GraphQL-LD.js#21]
**The answer to your response**

I don't think you're an expert to ask you in JavaScript
If you are an expert, write the correct code
Instead, I had to ask an expert and good person

When I thought to send you a message
Because the code did not work
I thought you were wrong and something you missed
I never thought you were an ignorant person
And you think that yourself is bigger than your real size
I do not need  to you and your programs

**Block**

**Comment by rubensworks** [comment]
This is not a GraphQL-LD problem, but a misunderstanding of the JavaScript language on your end.
Please learn more about variable scoping and async functions in JavaScript on your own, I am not your personal help for JavaScript problems.

I would also appreciate if you would stop emailing me about these problems.
If you have GraphQL-LD-specific problems, you are welcome to mail me, but not for generic problems with JavaScript.

**Comment by shaqura** [comment]
Block
--
Envoyé depuis l'application Outlook Email App pour Android jeudi, 26 mars 2020, 09:27AM +01:00 de Ruben Taelman  notifications@github.com :
