### ISSUE TITLE
Error: requires a single source with an rdfjsSource to be present in the context.

### ISSUE THREAD

**Issue by matheusriios** [rubensworks/GraphQL-LD.js#34]
```
    Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-queryoperators.json#mediatorResolveQuadPattern mediated over all rejecting actors:
    https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-rdfjs.json#myRdfRdfJsSourceQuadPatternResolver requires a single source with an rdfjsSource to be present in the context.
    Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-federated.json#myFederatedQuadPatternResolver can only resolve quad pattern queries against a sources array.
    Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-hypermedia.json#myQuadPatternHypermediaResolver can only resolve quad pattern queries against a single source.
        at /app/node_modules/@comunica/mediator-race/lib/MediatorRace.js:22:32
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

My code:

![Captura de tela de 2021-05-05 12-40-46](https://user-images.githubusercontent.com/30212080/117169404-74728680-ad9f-11eb-89ac-5dc61663baa7.png)

**Comment by matheusriios** [comment]
> ```
>     Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-queryoperators.json#mediatorResolveQuadPattern mediated over all rejecting actors:
>     https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-rdfjs.json#myRdfRdfJsSourceQuadPatternResolver requires a single source with an rdfjsSource to be present in the context.
>     Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-federated.json#myFederatedQuadPatternResolver can only resolve quad pattern queries against a sources array.
>     Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-hypermedia.json#myQuadPatternHypermediaResolver can only resolve quad pattern queries against a single source.
>         at /app/node_modules/@comunica/mediator-race/lib/MediatorRace.js:22:32
>         at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```
> 
> My code:
> 
> ![Captura de tela de 2021-05-05 12-40-46](https://user-images.githubusercontent.com/30212080/117169404-74728680-ad9f-11eb-89ac-5dc61663baa7.png)

**Comment by rubensworks** [comment]
The argument you pass to `QueryEngineComunica` is incorrect, it must be a hash containing a `sources` entry, as shown in the example: https://github.com/rubensworks/GraphQL-LD.js#with-a-client-side-query-engine
Applying this change will make things work.
