### ISSUE TITLE
Generating a Graphql Schema

### ISSUE THREAD

**Issue by azizbodal** [rubensworks/GraphQL-LD.js#39]
I was looking to create a graphql endpoint along with a graphiql UI. Is there a way to generate a graphql schema from the context or possibly the triple store (ex. the defined SHACL)?

I also opened up a discussion in the [Comunica discussion board](https://github.com/comunica/comunica/discussions/968).

Thanks.

**Comment by rubensworks** [comment]
Closing this issue in favor of https://github.com/comunica/comunica/discussions/968
