### ISSUE TITLE
No support for pagination: OFFSET, LIMIT, ORDER BY

### ISSUE THREAD

**Issue by sparkling** [rubensworks/GraphQL-LD.js#49]
Seems like this is missing, which makes the tool unusable for anything but the smallest of datasets. What would be involved for adding this? Can I help?

**Comment by rubensworks** [comment]
Offset and limit should be possible via `first` and `offset`: https://github.com/rubensworks/graphql-to-sparql.js#pagination

**Comment by sparkling** [comment]
Thanks - but how about ordering? Without ordering, pagination is non-deterministic in some cases

**Comment by rubensworks** [comment]
Ordering is not possible yet indeed. Might be possible to add it similar to the `first` and `offset` keywords.
PRs are definitely welcome on https://github.com/rubensworks/graphql-to-sparql.js
