### ISSUE TITLE
Context object is changed by the engine

### ISSUE THREAD

**Issue by pheyvaer** [rubensworks/GraphQL-LD.js#8]
The context object is changed when the engine executes the query. This is important to know if you want to reuse the context for something later on. I would suggest to add this to the docs/README.

**Comment by rubensworks** [comment]
Hmm, it shouldn't be changed though, so I'll classify this as a bug.

**Comment by pheyvaer** [comment]
Ooh ok. The thing that I noticed is that `{@reverse: "http://example.com/"}` gets converted to `{@reverse: true, @id: "http://example.com/"}`.
